#
# docker-compose.yml
#
---
version: '2'
services:
  hub:
    image: selenium/hub:3.141.59-20201119
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_HOST: hub